[project]
name = "clinical-trials"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "a1facts>=0.1.6",
    "agno>=1.8.1",
]
